### PR TITLE
Jan CR5 release

### PR DESCRIPTION
**Pull request by sabrina-yee**
- Automate CNX7 spring dependencies update (KB0099835)[https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0099835]
- Harbor OCI support to install / upgrade Helm charts from OCI registry in Harbor.
- Install K8s 1.28
- Support AlmaLinux9 as target Connections environment

### CODE REVIEW

**Comment by stoeps13** [comment]
Hi @sabrina-yee,
since the update to the OCI version of Helm charts, these are not visible in harbor:

image

I would expect a January version.

Is there a setting missing in harbor? It's quite useful for troubleshooting, using harbor to review the helm charts. 
Regards,
Christoph

**Comment by sabrina-yee** [comment]
Hi @stoeps13, the Helm charts are now in the `Repositories` tab instead.  For `infrastructure`, it's in https://hclcr.io/harbor/projects/15/repositories/infrastructure/artifacts-tab

If there is any issues accessing the charts, please let us know.

Thanks,
-Sabrina

**Comment by stoeps13** [comment]
It seems something has changed, now I see these artifacts, but I miss the images view. 

Has something changed since I wrote in the morning? When I login to Harbor and click Projects > cnx: I'm now in the artifacts view, in the morning I saw the different images of a project.

**Comment by sabrina-yee** [comment]
> It seems something has changed, now I see these artifacts, but I miss the images view.
> 
> ~Has something changed since I wrote in the morning? When I login to Harbor and click Projects > cnx: I'm now in the artifacts view, in the morning I saw the different images of a project.~
> 
> Ah, ok now artifacts shows both images and charts. Infrastructure has no images.

Not that I'm aware of, but there were some cloud related issues earlier so not sure if it's related.
That's correct, `Infrastructure` is only the chart as the images are under their corresponding name.

**Comment by stoeps13** [comment]
Thanks for the heads-up and the quick response. Happy to see everything now.

**Pull request merged**
